### ISSUE TITLE
Support new android build process

### ISSUE THREAD

**Issue by AlexAUT** [binary1248/SFML-Buildbot#14]
https://github.com/SFML/SFML/pull/1350
This PR will change the way SFML is build for android. There is no need to use a custom toolchain anymore. We just have to set two variables:

-DCMAKE_SYSTEM_NAME="Android"
-DCMAKE_ANDROID_NDK="PATH_TO_NDK"

optionally:
-DCMAKE_ANDROID_STL_TYPE="c++_shared"

Here are the codelines to change:
https://github.com/SFML/SFML-Buildbot/blob/2dd8ef943a6fcbfce413fc9c42e1e4fb870dc1b6/buildfactories.py#L58-L60

I would do a PR, but I do not know how to add the path of the NDK

**Comment by binary1248** [comment]
Fixed in local version. Will push at some point.
