### ISSUE TITLE
Preparations for unit tests

### ISSUE THREAD

**Issue by eXpl0it3r** [binary1248/SFML-Buildbot#20]
In preparations for the unit tests (https://github.com/SFML/SFML/pull/1475) we should only build and run the test suite for one configuration. Currently the easiest solution is to just do it with SFML linked statically, so one doesn't have to care about the shared library.

**Comment by TankOs** [comment]
Why only for one configuration? Isn't the reason for unit tests to see if it works everywhere? ;-)
