### ISSUE TITLE
Enforce use of `override` in CI 

### ISSUE THREAD

**Issue by vittorioromeo** [binary1248/SFML-Buildbot#28]
After https://github.com/SFML/SFML/pull/1878 is merged, we should make sure that missing `override` causes a CI failure.

**Comment by binary1248** [comment]
This should be handled as an issue in the main repository. The advantage is that enabling additional warnings as part of a PR will trigger CI with the new warnings so any changes to the code that become necessary to get the project to build again can become part of the same PR.

We can also use the opportunity to enable warnings for other language feature situations as well.
