### ISSUE TITLE
Add build job with SFML_ENABLE_PCH=1

### ISSUE THREAD

**Issue by vittorioromeo** [binary1248/SFML-Buildbot#41]
Useful to catch regressions with PCH support enabled.

**Comment by eXpl0it3r** [comment]
I guess the question is, whether we should expand the buildbot matrix or expand the GitHub Actions matrix.

What do you think, @ChrisThrasher?

**Comment by ChrisThrasher** [comment]
I'd rather do more work in GitHub Actions since it's tied to version control. I'd prefer if the Buildbot was reserved for things that are unfeasible in GitHub Actions like building on FreeBSD or with MinGW.

**Comment by binary1248** [comment]
As @ChrisThrasher said, buildbot is preferred when we are building for exotic configurations. If something can be tested on the VMs that actions provides it should be preferred instead.
