### ISSUE TITLE
Don't assume everybody uses Makefiles

### ISSUE THREAD

**Issue by JonnyPtn** [binary1248/SFML-Buildbot#9]
I've been taking a look at adding an iOS build using Xcode to this config, and noticed that the current setup is very reliant on the build using Makefiles (specifically [here](https://github.com/SFML/SFML-Buildbot/blob/master/buildfactories.py#L106)) , which seems an unnecessary restriction

I'd suggest using the make build command instead (i.e. `cmake --build .`instead of `make`) which will allow just as much configurability but will work with other cmake generators such as Xcode and visual studio

if there's no objections I'm happy to have a go at this change and include the iOS and visual studio build configurations

**Comment by eXpl0it3r** [comment]
Sounds good to me.

**Comment by mantognini** [comment]
Seems to be an appropriate change. :)
